DATASET:
  NAME: 'HyRANK'
  ROOT: 'E:/zzy/GAN/data/HyRANK'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'


DATALOADER:
  BATCH_SIZE: 32
  NUM_WORKERS: 0
  ITERATION: 626

MODEL:
  NAME: 'dsn_inn'
  BACKBONE: 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'softmax+ce'
    - 'orthogonal'
    - 'l2dis'
    - 'var'
  WEIGHTS:
    - 1.0
    - 1.0
    - 0.5
    - 0.5
    - 0.5

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 20
