DATASET:
  NAME: 'Indiana'
  ROOT: 'E:/zzy/GAN/data/Indiana'
  PATCH:
    HEIGHT: 11
    WIDTH: 11
    PAD_MODE: 'symmetric'
  SAMPLE_NUM: 1800
  SAMPLE_ORDER: 'average'

DATALOADER:
  BATCH_SIZE: 64
  NUM_WORKERS: 0
  ITERATION: 658

MODEL:
  NAME: 'dann'
  BACKBONE: 'resnet18'

CRITERION:
  ITEMS:
    - 'softmax+ce'
    - 'softmax+ce'
  WEIGHTS:
    - 1.0
    - 1.0

OPTIMIZER:
  NAME: 'adam'
  LR: 0.001

SCHEDULER:
  NAME: 'plateau'
  MODE: 'min'
  FACTOR: 0.1
  PATIENCE: 2

EPOCHS: 15
